### ISSUE TITLE
Not working on PyTorch 2.1 and CUDA 11.8

### ISSUE THREAD

**Issue by NikolaZubic** [lucidrains/jax2torch#4]
When I run this on PyTorch 2.1 and CUDA 11.8, I get this error:
Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "/home/nzubic/anaconda3/envs/events_signals/lib/python3.11/site-packages/jax2torch/jax2torch.py", line 54, in inner
    return JaxFun.apply(*bound.arguments.values())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nzubic/anaconda3/envs/events_signals/lib/python3.11/site-packages/torch/autograd/function.py", line 542, in apply
    raise RuntimeError(
RuntimeError: In order to use an autograd.Function with functorch transforms (vmap, grad, jvp, jacrev, ...), it must override the setup_context staticmethod. For more details, please see https://pytorch.org/docs/master/notes/extending.func.html

**Comment by lucidrains** [comment]
@NikolaZubic you are using functorch? yea this may be out of the scope of what this library can handle
